import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import FooterBolum from "@/components/footer";
import Head from 'next/head';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HDFİLMCEHENNEMİ",
  description: "Generated by mevocan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-100	 p-4 lg:px-20 flex flex-col  min-h-screen`}>
        
        <Header />
        <main className="grow p-5">{children}</main>
        <FooterBolum />
      </body>
    </html>
  );
}
